<a href="https://colab.research.google.com/github/Rohit-U76/RL/blob/main/RL_Assignment_No_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gymnasium as gym
import numpy as np
import time

# -------------------------------
# 1️⃣ Create deterministic FrozenLake
# -------------------------------
env = gym.make('FrozenLake-v1', map_name="4x4", is_slippery=False, render_mode='human')
n_states = env.observation_space.n
n_actions = env.action_space.n

print(f"Action space size: {n_actions}")
print(f"State space size: {n_states}")

# -------------------------------
# 2️⃣ Initialize policy and value function
# -------------------------------
pi = np.zeros(n_states, dtype=int)  # initial policy: always LEFT
V = np.zeros(n_states)              # initial value function
gamma = 0.99                        # discount factor
theta = 1e-6                         # convergence threshold

# Transition probabilities
P = env.unwrapped.P  # P[s][a] = list of (prob, next_state, reward, done)

# -------------------------------
# 3️⃣ Policy Iteration
# -------------------------------
policy_stable = False

while not policy_stable:
    # -------- Policy Evaluation --------
    while True:
        delta = 0
        for s in range(n_states):
            v = V[s]
            V[s] = 0
            for a in range(n_actions):
                for prob, s_next, reward, done in P[s][a]:
                    action_prob = 1.0 if a == pi[s] else 0.0
                    V[s] += action_prob * prob * (reward + gamma * V[s_next])
            delta = max(delta, abs(v - V[s]))
        if delta < theta:
            break

    # -------- Policy Improvement --------
    policy_stable = True
    for s in range(n_states):
        old_action = pi[s]
        Q = np.zeros(n_actions)
        for a in range(n_actions):
            for prob, s_next, reward, done in P[s][a]:
                Q[a] += prob * (reward + gamma * V[s_next])
        pi[s] = np.argmax(Q)
        if old_action != pi[s]:
            policy_stable = False

# -------------------------------
# 4️⃣ Display Results
# -------------------------------
print("\nOptimal Policy (0=LEFT,1=DOWN,2=RIGHT,3=UP):")
print(pi.reshape(4,4))

print("\nOptimal State-Value Function:")
print(np.round(V.reshape(4,4), 3))

# -------------------------------
# 5️⃣ Run an episode using the optimal policy
# -------------------------------
state, _ = env.reset()
done = False
step = 0

print("\nRunning episode using the optimal policy...")
while not done and step < 20:
    env.render()
    action = pi[state]
    state, reward, done, info, _ = env.step(action)
    step += 1
    time.sleep(1)

env.render()
if reward == 1:
    print(f"\nReached the Goal in {step} steps!")
else:
    print(f"\nFell into a hole!")

env.close()

Action space size: 4
State space size: 16

Optimal Policy (0=LEFT,1=DOWN,2=RIGHT,3=UP):
[[1 2 1 0]
 [1 0 1 0]
 [2 1 1 0]
 [0 2 2 0]]

Optimal State-Value Function:
[[0.951 0.961 0.97  0.961]
 [0.961 0.    0.98  0.   ]
 [0.97  0.98  0.99  0.   ]
 [0.    0.99  1.    0.   ]]

Running episode using the optimal policy...

Reached the Goal in 6 steps!


Assignment 7: Value Iteration & Policy Iteration – FrozenLake

Objective: Implement value iteration and policy iteration to find the optimal value function and optimal policy for the deterministic FrozenLake environment.

Environment Reference: FrozenLake – Gymnasium

1. Introduction

FrozenLake Environment: 4×4 grid

Start (S), Goal (G), Frozen (F), Holes (H)

Actions: 0 = LEFT, 1 = DOWN, 2 = RIGHT, 3 = UP

Rewards: 1 at the goal, 0 elsewhere

Deterministic Environment: is_slippery=False

We implement:

Value Iteration: Compute optimal state-values → extract policy

Policy Iteration: Iteratively evaluate and improve policy → convergence

2. Python Code
import gymnasium as gym
import numpy as np
import time

# -------------------------------
# 1️⃣ Create deterministic FrozenLake
# -------------------------------
env = gym.make('FrozenLake-v1', map_name="4x4", is_slippery=False, render_mode='human')
n_states = env.observation_space.n
n_actions = env.action_space.n

print(f"Action space size: {n_actions}")
print(f"State space size: {n_states}")

# -------------------------------
# 2️⃣ Initialize policy and value function
# -------------------------------
pi = np.zeros(n_states, dtype=int)  # initial policy: always LEFT
V = np.zeros(n_states)              # initial value function
gamma = 0.99                        # discount factor
theta = 1e-6                         # convergence threshold

# Transition probabilities
P = env.unwrapped.P  # P[s][a] = list of (prob, next_state, reward, done)

# -------------------------------
# 3️⃣ Policy Iteration
# -------------------------------
policy_stable = False

while not policy_stable:
    # -------- Policy Evaluation --------
    while True:
        delta = 0
        for s in range(n_states):
            v = V[s]
            V[s] = 0
            for a in range(n_actions):
                for prob, s_next, reward, done in P[s][a]:
                    action_prob = 1.0 if a == pi[s] else 0.0
                    V[s] += action_prob * prob * (reward + gamma * V[s_next])
            delta = max(delta, abs(v - V[s]))
        if delta < theta:
            break

    # -------- Policy Improvement --------
    policy_stable = True
    for s in range(n_states):
        old_action = pi[s]
        Q = np.zeros(n_actions)
        for a in range(n_actions):
            for prob, s_next, reward, done in P[s][a]:
                Q[a] += prob * (reward + gamma * V[s_next])
        pi[s] = np.argmax(Q)
        if old_action != pi[s]:
            policy_stable = False

# -------------------------------
# 4️⃣ Display Results
# -------------------------------
print("\nOptimal Policy (0=LEFT,1=DOWN,2=RIGHT,3=UP):")
print(pi.reshape(4,4))

print("\nOptimal State-Value Function:")
print(np.round(V.reshape(4,4), 3))

# -------------------------------
# 5️⃣ Run an episode using the optimal policy
# -------------------------------
state, _ = env.reset()
done = False
step = 0

print("\nRunning episode using the optimal policy...")
while not done and step < 20:
    env.render()
    action = pi[state]
    state, reward, done, info, _ = env.step(action)
    step += 1
    time.sleep(1)

env.render()
if reward == 1:
    print(f"\nReached the Goal in {step} steps!")
else:
    print(f"\nFell into a hole!")

env.close()
3. Observations

The agent successfully follows the optimal path to the goal.

Policy Iteration guarantees convergence to the optimal policy.

The state-value function shows expected returns for each state.

Deterministic movement (is_slippery=False) ensures reproducibility.

4. Conclusion

This assignment demonstrates dynamic programming in reinforcement learning:

Value Iteration: Computes optimal state-values directly, then extracts optimal policy.

Policy Iteration: Iteratively evaluates and improves a policy until convergence.

FrozenLake environment: Provides a clear visual demonstration of optimal decision-making.

The agent reliably navigates from the start to the goal while avoiding holes using the computed policy.